# Generated by Django 3.0.14 on 2021-06-28 23:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('lifter', '0001_initial'), ('lifter', '0002_auto_20210518_0019'), ('lifter', '0003_auto_20210518_0043'), ('lifter', '0004_auto_20210518_0047'), ('lifter', '0005_auto_20210518_2348'), ('lifter', '0006_auto_20210519_0004'), ('lifter', '0007_auto_20210628_2317'), ('lifter', '0008_auto_20210628_2335')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('org_number', models.CharField(blank=True, max_length=10, null=True)),
                ('rf_number', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('U', 'Ungdom'), ('J', 'Junior'), ('S', 'Senior'), ('M1', 'Veteran (40-49 år)'), ('M2', 'Veteran (50-59 år)'), ('M3', 'Veteran (60-69 år)'), ('M4', 'Veteran (70-79 år)')], max_length=2)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categories', to='lifter.AgeBracket')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighin_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EBP', 'Utrustad Bänkpress'), ('CPL', 'Klassiskt Styrkelyft'), ('EPL', 'Utrustat Styrkelyft'), ('CBP', 'Klassisk Bänkpress'), ('PBP', 'Paralympisk Bänkpress')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('postal_city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SQ', 'Knäböj'), ('BP', 'Bänkpress'), ('DL', 'Marklyft')], max_length=2)),
                ('competition_type', models.ManyToManyField(to='lifter.CompetitionType')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('stop', models.DateField()),
                ('max_lifters', models.PositiveIntegerField()),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.CompetitionType')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IPF', 'IPF-poäng'), ('WLK', 'Wilks-poäng')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='lifter.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.District')),
                ('org_number', models.CharField(blank=True, max_length=10, null=True)),
                ('rf_number', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_information', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lifter.ContactInformation')),
                ('fees', models.ManyToManyField(to='lifter.Fee')),
            ],
        ),
        migrations.CreateModel(
            name='Lifter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=2)),
                ('id_number', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('contact_information', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lifter.ContactInformation')),
                ('clubs', models.ManyToManyField(related_name='lifters', to='lifter.Club')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('requested', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('LI', 'Licensierad'), ('EL', 'Ej licensierad')], max_length=2)),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='lifter.Lifter')),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to='lifter.Club')),
            ],
            options={
                'unique_together': {('number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.ManyToManyField(to='lifter.CollectedResult')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.Round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='lifter.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.Club'),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='lifter.Division'),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.DecimalField(decimal_places=1, max_digits=4)),
                ('collected_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_results', to='lifter.CollectedResult')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='NationalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('last_signup', models.DateField()),
                ('categories', models.ManyToManyField(to='lifter.Category')),
                ('competition_types', models.ManyToManyField(to='lifter.CompetitionType')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifter.Contact')),
                ('documents', models.ManyToManyField(to='lifter.Document')),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifter.Club')),
                ('affects_ranking', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='point_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.PointSystem'),
        ),
        migrations.CreateModel(
            name='DistrictAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', models.ManyToManyField(to='lifter.District')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.Invitation')),
                ('results', models.ManyToManyField(to='lifter.CollectedResult')),
            ],
        ),
        migrations.AddField(
            model_name='collectedresult',
            name='lifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.Lifter'),
        ),
        migrations.AddField(
            model_name='collectedresult',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.WeightClass'),
        ),
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubs', models.ManyToManyField(to='lifter.Club')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_categories', to='lifter.WeightClass'),
        ),
        migrations.AddField(
            model_name='district',
            name='contact_information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lifter.ContactInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='contacts',
            field=models.ManyToManyField(to='lifter.Lifter'),
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=2),
        ),
        migrations.CreateModel(
            name='QualificationLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_limit', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.Category')),
            ],
        ),
        migrations.CreateModel(
            name='JudgeLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_level', models.CharField(choices=[('DD', 'Distriktsdomare'), ('FD', 'Förbundsdomare')], max_length=2)),
                ('book_number', models.PositiveIntegerField()),
                ('approved', models.BooleanField()),
                ('year', models.PositiveIntegerField()),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_credentials', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionOrganizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_organizer', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='qualification_levels',
            field=models.ManyToManyField(to='lifter.QualificationLevels'),
        ),
    ]
