# Generated by Django 2.2 on 2019-04-07 16:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lifter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('postal_city', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=1)),
                ('id_number', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.Club')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8)),
                ('year', models.PositiveIntegerField()),
                ('requested', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('LI', 'Licensierad'), ('EL', 'Ej licensierad')], max_length=2)),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.Lifter')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.District'),
        ),
    ]
