# Generated by Django 2.1.7 on 2019-04-02 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import lifter.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=8)),
                ('license_year', models.PositiveIntegerField()),
                ('license_requested', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('license_status', models.CharField(choices=[(lifter.models.LicenseStatus('Licensierad'), 'Licensierad'), (lifter.models.LicenseStatus('Ej licensierad'), 'Ej licensierad')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Lifter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('family_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=10)),
                ('postal_city', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[(lifter.models.Gender('Man'), 'Man'), (lifter.models.Gender('Kvinna'), 'Kvinna')], max_length=1)),
                ('id_number', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[(lifter.models.Role('Ingen roll'), 'Ingen roll'), (lifter.models.Role('Förbundsadministratör'), 'Förbundsadministratör'), (lifter.models.Role('Distriktsadministratör'), 'Distriktsadministratör'), (lifter.models.Role('Föreningsadministratör'), 'Föreningsadministratör')], max_length=2)),
                ('club', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.District')),
            ],
        ),
        migrations.AddField(
            model_name='license',
            name='lifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.Lifter'),
        ),
    ]
