# Generated by Django 3.0.14 on 2021-05-18 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('U', 'Ungdom'), ('J', 'Junior'), ('S', 'Senior'), ('M1', 'Veteran (40-49 år)'), ('M2', 'Veteran (50-59 år)'), ('M3', 'Veteran (60-69 år)'), ('M4', 'Veteran (70-79 år)')], max_length=2)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categories', to='lifter.AgeBracket')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weighin_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.Category')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('EBP', 'Utrustad Bänkpress'), ('CPL', 'Klassiskt Styrkelyft'), ('EPL', 'Utrustat Styrkelyft'), ('CBP', 'Klassisk Bänkpress')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('postal_city', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SQ', 'Knäböj'), ('BP', 'Bänkpress'), ('DL', 'Marklyft')], max_length=2)),
                ('competition_type', models.ManyToManyField(to='lifter.CompetitionType')),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('stop', models.DateField()),
                ('max_lifters', models.PositiveIntegerField()),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.CompetitionType')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PointSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IPF', 'IPF-poäng'), ('WLK', 'Wilks-poäng')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='lifter.Division')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeightClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='lifter',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lifter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lifter',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lifter',
            name='postal_city',
        ),
        migrations.RemoveField(
            model_name='lifter',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='club',
            name='org_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='rf_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='contacts',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contact_for_districts', to='lifter.Lifter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='org_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='rf_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='licenses', to='lifter.Club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.District'),
        ),
        migrations.AlterField(
            model_name='license',
            name='lifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='lifter.Lifter'),
        ),
        migrations.AlterField(
            model_name='license',
            name='requested',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lifter',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lifters', to='lifter.Club'),
        ),
        migrations.AlterField(
            model_name='lifter',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('number', 'year')},
        ),
        migrations.CreateModel(
            name='TeamResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.ManyToManyField(to='lifter.CollectedResult')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.Round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_results', to='lifter.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.Club'),
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teams', to='lifter.Division'),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removed', models.BooleanField(default=False)),
                ('order_number', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.DecimalField(decimal_places=1, max_digits=4)),
                ('collected_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_results', to='lifter.CollectedResult')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='NationalAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='national_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_level', models.CharField(choices=[('DD', 'Distriktsdomare'), ('FD', 'Förbundsdomare')], max_length=2)),
                ('book_number', models.PositiveIntegerField()),
                ('approved', models.BooleanField()),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_credentials', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('last_signup', models.DateField()),
                ('qualification', models.BooleanField()),
                ('categories', models.ManyToManyField(to='lifter.Category')),
                ('competition_types', models.ManyToManyField(to='lifter.CompetitionType')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifter.Contact')),
                ('documents', models.ManyToManyField(to='lifter.Document')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifter.Club')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='point_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.PointSystem'),
        ),
        migrations.CreateModel(
            name='DistrictAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', models.ManyToManyField(to='lifter.District')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifter.Invitation')),
                ('results', models.ManyToManyField(to='lifter.CollectedResult')),
            ],
        ),
        migrations.AddField(
            model_name='collectedresult',
            name='lifter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.Lifter'),
        ),
        migrations.AddField(
            model_name='collectedresult',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='lifter.WeightClass'),
        ),
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubs', models.ManyToManyField(to='lifter.Club')),
                ('lifter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_admin', to='lifter.Lifter')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_categories', to='lifter.Gender'),
        ),
        migrations.AddField(
            model_name='category',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_categories', to='lifter.WeightClass'),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lifter.ContactInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='club',
            name='fees',
            field=models.ManyToManyField(to='lifter.Fee'),
        ),
        migrations.AddField(
            model_name='district',
            name='contact_information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lifter.ContactInformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lifter',
            name='contact_information',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lifter.ContactInformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lifter',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='lifter.Gender'),
        ),
    ]
