# Generated by Django 5.2.7 on 2025-11-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='name',
            field=models.CharField(choices=[('EB', 'Utrustad Bänkpress'), ('CP', 'Klassiskt Styrkelyft'), ('EP', 'Utrustat Styrkelyft'), ('CB', 'Klassisk Bänkpress'), ('PB', 'Paralympisk Bänkpress')], max_length=3),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(choices=[('S', 'Knäböj'), ('B', 'Bänkpress'), ('D', 'Marklyft'), ('P', 'Paralympisk Bänkpress')], max_length=2),
        ),
        migrations.AlterField(
            model_name='judgelicense',
            name='judge_level',
            field=models.CharField(choices=[('D', 'Distriktsdomare'), ('F', 'Förbundsdomare')], max_length=2),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('L', 'Licensierad'), ('N', 'Ej licensierad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pointsystem',
            name='name',
            field=models.CharField(choices=[('I', 'IPF-poäng'), ('W', 'Wilks-poäng')], max_length=3),
        ),
    ]
