# Generated by Django 3.0.14 on 2021-05-18 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0002_auto_20210518_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifter.Contact'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lifter.Club'),
        ),
    ]
