# Generated by Django 2.1.7 on 2019-04-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0002_auto_20190402_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_status',
            field=models.CharField(choices=[('LI', 'Licensierad'), ('EL', 'Ej licensierad')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lifter',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=1),
        ),
    ]
