# Generated by Django 5.2.7 on 2025-11-02 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0002_alter_competitiontype_name_alter_discipline_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionadmin',
            name='competitions',
            field=models.ManyToManyField(to='lifter.competition'),
        ),
        migrations.AddField(
            model_name='competitionorganizer',
            name='competitions',
            field=models.ManyToManyField(to='lifter.competition'),
        ),
        migrations.AlterField(
            model_name='club',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='lifter.district'),
        ),
    ]
