# Generated by Django 3.0.14 on 2021-05-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0003_auto_20210518_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='contacts',
        ),
        migrations.AddField(
            model_name='district',
            name='contacts',
            field=models.ManyToManyField(to='lifter.Lifter'),
        ),
    ]
