# Generated by Django 2.2 on 2019-04-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0003_auto_20190403_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifter',
            name='district',
        ),
        migrations.AddField(
            model_name='club',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='lifter.District'),
            preserve_default=False,
        ),
    ]
