# Generated by Django 3.0.14 on 2021-05-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0004_auto_20210518_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], default='F', max_length=2),
        ),
        migrations.AlterField(
            model_name='lifter',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], default='F', max_length=2),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
