# Generated by Django 2.2 on 2019-04-06 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0004_auto_20190406_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='license_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='license_requested',
            new_name='requested',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='license_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='license',
            old_name='license_year',
            new_name='year',
        ),
    ]
