# Generated by Django 3.0.14 on 2021-05-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifter', '0005_auto_20210518_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lifter',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Kvinna')], max_length=2),
        ),
    ]
